version: "3.9"
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      TZ: "Europe/Stockholm"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: srai
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
